### ISSUE TITLE
S3 compatible blob storage configuration

### ISSUE THREAD

**Issue by aitorhh** [foxglove/helm-charts#104]
**Description**

When trying the self-hosted deployment of foxgrove based on the [documentation provided](https://docs.foxglove.dev/docs/primary-sites/self-hosting/installation/), the S3 compatible storage solution for inbox-listener and stream-service does not work

- Version: CHART primary-site-0.0.52; APP VERSION: 79aed2aaac91cb942467185b7c1f74454cb0fefe
- Platform: kubernetes v1.27

**Steps To Reproduce**

As in the documentation, using the following as `values.yaml`
```
globals:
  lake:
    storageProvider: s3_compatible
    bucketName: foxglove-lake
  inbox:
    storageProvider: s3_compatible
    bucketName: foxglove-inbox

```
Then installing with 
```
helm repo add foxglove https://helm-charts.foxglove.dev
helm repo update
helm upgrade --install foxglove-primary-site foxglove/primary-site \
    --values ./values.yaml  \
    --namespace foxglove \
    --create-namespace
```

The PODs are failing with:
> {"message":"Failed to initialize inbox store: S3CompatibleServiceURL must be configured","severity":"FATAL","timestamp":""}

**Expected Behavior**
A working system with self-storage in own cluster.

- The following gaps in documentation:
* How to provide `serviceUrl` or `S3CompatibleServiceURL` for s3_compatible?
* How to provide the secrets for the s3_compatible
